runtime: php55
api_version: 1

handlers:
- url: /(.*\.(gif|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(gif|jpeg|jpg|png))
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /css
  static_dir: css

- url: /js
  static_dir: js


- url: /.*
  script: index.php
