runtime: php55
api_version: 1

builtins:
- remote_api: on


handlers:
- url: /(.*\.(gif|jpeg|jpg|png))
  static_files: static/\1
  upload: src/static/(.*\.(gif|jpeg|jpg|png))
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /css
  static_dir: src/css

- url: /js
  static_dir: src/js

- url: /blog
  script: src/blog.php

- url: /blog/.*
  script: src/blog.php

- url: /.*
  script: src/index.php

skip_files:
  - ^(.*/)node_modules/(.*/)?
  - ^\.git/.*
