runtime: php55
api_version: 1


builtins:
- remote_api: on

handlers:
- url: /(.*\.(gif|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(gif|jpeg|jpg|png))
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /blog
  script: blog.php

- url: /blog/.*
  script: blog.php

- url: /.*
  script: index.php
